Import('*')

srcs = SGlob( '*.cpp' )
                
deps = [ 'dtCore', 'openal', 'dtUtil', 'isense', 'OpenThreads',
         'osg', 'osgDB', 'osgParticle', 'osgText', 'osgUtil',
         'osgGA', 'osgSim', 'osgFX', 'osgProducer', 'ul', 'js', 'Producer',
         'opengl', 'alut', 'User32' ]

BuildLib( 'dtAudio', srcs, deps, ['DT_AUDIO_LIBRARY'] )
