Import('*')

dtVisSrcs = [ 'bspcullcallback.cpp' ]

env = env.Copy()

dtVisLib = env.SharedLibrary( 'dtvis', dtVisSrcs, LIBS=[ 'GL', 'osg', 'osgDB', 'osgUtil' ] )

env.Install( "$prefix/lib", dtVisLib )
