Import('*')

import glob

srcfiles = SGlob('*.cpp')

dtAbcDeps=[ 'dtcore', 'fltk', 'dtutil', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'osgGA', 'osgSim', 'osgFX', 'osgProducer','sg', 'ul', 'js', 'Producer', 'tinyxml', 'xerces-c', 'opengl' ]

if OS == 'windows' :
   dtAbcDeps += [ 'User32' ]
       
BuildLib( 'dtabc', srcfiles, dtAbcDeps, ['DT_LIBRARY'] )
