Import('*')

srcs = env.SGlob( '*.cpp' )
                
deps = [ 'dtCore', 'openal', 'alut', 'dtUtil', 'isense', 'OpenThreads',
         'osg', 'osgDB', 'osgParticle', 'osgText', 'osgUtil',
         'osgSim', 'osgFX', 'ul', 'js', 'Producer',
         'opengl', 'alut', 'User32' ]

defines = []
if env['OS'] == 'windows':
   defines = ['DT_AUDIO_LIBRARY', 'NOMINMAX']


env.BuildLib( 'dtAudio', srcs, deps, defines, prefixHeader = 'inc/prefix/dtcoreprefix.h' )
