# Build script for the testActorLibrary
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

if OS == 'darwin':
   overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   overrideShSuffix = '.so'
else:
   overrideShLink = ''
   overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = ['testactorlib.cpp', 'testpropertyproxy.cpp']

testActorsLibraryDeps =['dtDAL', 'dtutil', 'dtcore', 'ode',
        'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil',
        'osgGA', 'osgSim', 'osgFX', 'osgProducer', 'sg', 'ul', 'js',
        'Producer', 'tinyxml', 'opengl' ]

if OS == 'windows':
   testActorsLibraryDeps += ['dtActors']

if OS == 'windows' :
   testActorsLibraryDeps += [ 'dtsoarx', 'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32' ]
elif OS == 'linux':
   testActorsLibraryDeps += [ 'uuid', 'Xxf86vm' ]
elif OS == 'darwin':
   testActorsLibraryDeps += [ 'CoreFoundation', 'IOKit', 'Carbon' ]

if(OS == 'windows' and mode == 'debug') :
	testActorsLibrary = BuildLib( 'testActorsLibraryd', sources, testActorsLibraryDeps, ['DT_PLUGIN'], 
		overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix )
else :
	testActorsLibrary = BuildLib( 'testActorsLibrary', sources, testActorsLibraryDeps, ['DT_PLUGIN'], 
		overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix )


if OS == 'darwin':
   Depends(testActorsLibrary, libdtDAL)

Export('testActorsLibrary')
