# Build script for the testActorLibrary
import glob
import sys
import delta3d

# Import the variables defined in the global SConstruct build script.
Import ('*')

#if env['OS'] == 'darwin':
   #overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
#   overrideShSuffix = '.dylib'
#else:

overrideShLink = ''
overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = env.SGlob('*.cpp')

testActorLibraryDeps =[ 'dtDAL', 'dtUtil', 'dtCore', 'ode', 'OpenThreads', 'osg',
                        'osgDB', 'osgParticle', 'osgText', 'osgUtil',
                        'osgSim', 'osgFX',
                        'Producer', 'opengl', 'dtSORAX', 'User32',
                        'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
                        'CoreFoundation', 'IOKit', 'Carbon', 'dtActors' ]

#if env['OS'] == 'windows':
#   testActorLibraryDeps += ['dtActors']

testActorLibrary = env.BuildLib( 'testActorLibrary', sources, testActorLibraryDeps, ['DT_PLUGIN'], 
                             overrideShLinkFlags = overrideShLink,
                             overrideShLibSuffix = overrideShSuffix )

if env['OS'] == 'darwin':
   Depends(testActorLibrary, libdtDAL)

Export('testActorLibrary')
