# Build script for the testActorLibrary
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

if OS == 'darwin':
   overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   overrideShSuffix = '.dylib'
else:
   overrideShLink = ''
   overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = SGlob('*.cpp')

testActorLibraryDeps =[ 'dtDAL', 'dtUtil', 'dtCore', 'ode', 'OpenThreads', 'osg',
                        'osgDB', 'osgParticle', 'osgText', 'osgUtil',
                        'osgGA', 'osgSim', 'osgFX', 'osgProducer', 'ul', 'js',
                        'Producer', 'opengl', 'dtSORAX', 'User32',
                        'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
                        'CoreFoundation', 'IOKit', 'Carbon' ]

if OS == 'windows':
   testActorLibraryDeps += ['dtActors']

testActorLibrary = env.BuildLib( 'testActorLibrary', sources, testActorLibraryDeps, ['DT_PLUGIN'], 
                             overrideShLinkFlags = overrideShLink,
                             overrideShLibSuffix = overrideShSuffix )

if OS == 'darwin':
   Depends(testActorLibrary, libdtDAL)

Export('testActorLibrary')
