Import('*')

dtAudioSrcs = [ 'audiomanager.cpp',
                'listener.cpp',
                'sound.cpp',
                'soundeffectbinder.cpp' ]
                
dtAudioDeps = [ 'openal', 'OpenThreads', 'osg', 'osgDB', 'sg', 'ul', 'Producer', 'tinyxml' ]

if OS == 'windows' :
    dtAudioDeps += ['alut', 'User32']

dtAudioDeps = [ extLibs[lib] for lib in dtAudioDeps if extLibs.has_key(lib) ] + ['dtcore']

build_delta3d_lib( 'dtaudio', dtAudioSrcs, dtAudioDeps )