Import('*')

env = env.Copy()

bspCompiler = env.Program( 'bspCompiler', ['splitgeode.cpp', 'main.cpp'], LIBS=[ 'dtvis', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer' ] )
