import os
import glob
import re
import string

Import('*')

if env.get('rti') != 0 :

   dtHlaSrcs = [  'dis_types.cpp',
                  'entity.cpp',
                  'rticonnection.cpp' ]
                  
   dtHlaDeps = [ 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgUtil', 'osgSim', 'osgText', 'sg', 'ul', 'Producer', 'tinyxml' ]
   
   if OS == 'windows' :
      dtHlaDeps += ['User32','winsock']
      
   dtHlaDeps = [ extLibs[lib] for lib in dtHlaDeps if extLibs.has_key(lib) ] + rtiSLibs + ['dtcore']
             
   dtHlaLib = env.SharedLibrary( 'dthla', dtHlaSrcs, CPPDEFINES = env['CPPDEFINES']+['DT_LIBRARY'], LIBS = dtHlaDeps )

   env.Alias( 'install', env.Install( "$prefix/lib", dtHlaLib ) )
   env.Default( dtHlaLib )

