Import('*')

dtAbcLib = SConscript( 'dtABC/SConscript' )
dtAudioLib = SConscript( 'dtAudio/SConscript' )
dtCharLib = SConscript( 'dtChar/SConscript' )
dtCoreLib = SConscript( 'dtCore/SConscript' )
dtHlaLib = SConscript( 'dtHLA/SConscript' )
dtSoarxLib = SConscript( 'soarx/SConscript' )
dtUtilLib = SConscript( 'dtUtil/SConscript' )
dtVisLib = SConscript( 'dtVis/SConscript' )
gui_flLib = SConscript( 'gui_fl/SConscript' )
SConscript( 'python/SConscript' )

env.Default( dtAbcLib, dtAudioLib, dtCharLib, dtCoreLib, dtUtilLib, dtVisLib, gui_flLib)

#env.Depends( dtCoreLib, dtUtilLib )
#env.Depends( dtAbcLib, dtCoreLib )
#env.Depends( dtCharLib, dtCoreLib )
#env.Depends( gui_flLib, [ dtCoreLib, dtAbcLib ] )

#if dtSoarxLib is not None:
#    env.Depends( dtSoarxLib, dtCoreLib )

#if dtHlaLib is not None:
#    env.Depends( dtHlaLib, dtCoreLib )

#Return( 'dtAbcLib', 'dtAudioLib', 'dtCharLib', 'dtCoreLib', 'dtHlaLib', 'dtUtilLib', 'dtVisLib', 'gui_flLib' )

