Import('*')

if OS == 'windows' :

   testSrcs = [ 'testSoarx.cpp','main.cpp' ] 

   testDeps = [ 'dtcore', 'dtabc', 'dtutil', 'dtsoarx' ]

   BuildProgram( '#bin/testSoarx', testSrcs, testDeps )
   
