# Locate OpenThreads
# This module defines
# OPENTHREADS_LIBRARY
# OPENTHREADS_FOUND, if false, do not try to link to OpenThreads 
# OPENTHREADS_INCLUDE_DIR, where to find the headers
#
# $OPENTHREADS_DIR is an environment variable that would
# correspond to the ./configure --prefix=$OPENTHREADS_DIR
#
# Created by Robert Osfield
#   with revisions by the Delta3D team.

FIND_PATH(OPENTHREADS_INCLUDE_DIR OpenThreads/Thread
    PATH_SUFFIXES include inc Frameworks
    HINTS
    ${OPENTHREADS_DIR}
    $ENV{OPENTHREADS_DIR}
    ${DELTA3D_EXT_DIR}
    $ENV{DELTA_ROOT}/ext
    $ENV{OSG_DIR}
    $ENV{OSG_ROOT}
)
MARK_AS_ADVANCED(OPENTHREADS_INCLUDE_DIR)

MACRO(FIND_OPENTHREADS_LIBRARY MYLIBRARY MYLIBRARYNAME)
 
FIND_LIBRARY(${MYLIBRARY} 
        NAMES ${MYLIBRARYNAME}
        PATH_SUFFIXES lib build/lib lib64 build/lib64 Frameworks
        HINTS
        ${OPENTHREADS_DIR}
        $ENV{OSG_DIR}
        $ENV{OSGDIR}
        $ENV{OSG_ROOT}
        ${DELTA3D_EXT_DIR}
        $ENV{DELTA_ROOT}/ext
)
MARK_AS_ADVANCED(${MYLIBRARY})

ENDMACRO(FIND_OPENTHREADS_LIBRARY MYLIBRARY MYLIBRARYNAME)
 
 FIND_OPENTHREADS_LIBRARY(OPENTHREADS_LIBRARY OpenThreads OpenThreadsWin32)
 FIND_OPENTHREADS_LIBRARY(OPENTHREADS_LIBRARY_DEBUG OpenThreadsd)

SET(OPENTHREADS_FOUND "NO")
IF(OPENTHREADS_LIBRARY AND OPENTHREADS_INCLUDE_DIR)
    SET(OPENTHREADS_FOUND "YES")
ENDIF(OPENTHREADS_LIBRARY AND OPENTHREADS_INCLUDE_DIR)


