Import('*')


envCopy = env.Copy()

srcs = envCopy.SGlob( '*.cpp' )                  
deps = [ 'dtActors', 'dtGame', 'dtDAL', 'dtABC', 'dtCore', 'dtLMS', 'dtGUI', 'osgSim' ]

defines = []
if envCopy['OS'] == 'windows':
   defines = ['DELTA_FIRE_FIGHTER_LIBRARY']

envCopy.Append(CPPPATH = ['#demos'])

envCopy.BuildLib( 'fireFighter', srcs, deps, defines, 
	prefixHeader = 'inc/prefix/dtgameprefix.h' )
