Import('*')

dtScriptSrcs = [ 'scriptmanager.cpp' ]
dtScriptDeps = [ 'osg', 'python' ]

dtScriptDeps = [ extLibs[lib] for lib in dtScriptDeps if extLibs.has_key(lib) ] + [ 'dtcore' ]
    
build_delta3d_lib( 'dtscript', dtScriptSrcs, dtScriptDeps )
