import os

Import('*')

if CheckForBoost() :

   srcs = env.SGlob( '*.cpp' )
   deps = [ 'dtCore', 'dtABC', 'dtUtil', 'dtScript', 'python' ]

   extraLink = []
   if env['OS'] == 'windows':
      extraLink = ['/NODEFAULTLIB:'+ env['extLibs']['python']+'_d']

   env.BuildProgram( 'testPython', srcs, deps, [], extraLink )
