Import('*')

testSrcs = ['MyWidget.cpp', 'MyWindow.cpp', 'TestWidget.cxx' ]

testDeps = [ 'glgui', 'fltk', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal' ]

if OS == 'windows' :
   testDeps += [ 'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]
elif OS == 'linux' :
   testDeps += [ 'Xxf86vm' ]

testDeps = [ extLibs[lib] for lib in testDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtutil' ]

env.Program( 'testWidget', testSrcs, LIBS = testDeps )
