Import('*')

viewerSrcs = ['main.cpp', 'UserInterface.cxx', 'viewer.cpp', 'viewstate.cpp', 'viewwindow.cpp']

viewerDeps = [ 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'gdal' ]
                
if OS == 'windows' :
   viewerDeps += [ 'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]
elif OS == 'linux' :
   viewerDeps += ['Xxf86vm']

viewerDeps = [ extLibs[lib] for lib in viewerDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtutil' ]

env.Program( 'viewer', viewerSrcs, LIBS = viewerDeps )