Import('*')

viewerSrcs = SGlob( '*.cpp' ) + SGlob( '*.cxx' )

# Build the icon
if OS == 'windows' :
   viewerSrcs += env.RES( 'Viewer.rc' )

viewerDeps = [ 'dtDAL', 'dtCore', 'dtABC', 'dtUtil', 'dtChar',
               'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

env.BuildProgram( 'viewer', viewerSrcs, viewerDeps, buildAppBundle = 0 )
