Import('*')

viewerSrcs = ['main.cpp', 'UserInterface.cxx', 'viewer.cpp', 'viewstate.cpp', 'viewwindow.cpp']

viewerDeps = [ 'dtcore', 'dtabc', 'dtutil' ]

BuildProgram( 'viewer', viewerSrcs, viewerDeps )
