Import('*')

dtCharSrcs = [  'character.cpp' ]

if OS == 'darwin':
    dtCharDeps=[ 'dtcore', 'cal3d', 'rbody' ] 
else:
    dtCharDeps=[ 'dtcore', 'cal3d', 'rbody', 'rvrutils', 'rcfgscript' ] 
    
BuildLib( 'dtchar', dtCharSrcs, dtCharDeps, ['DT_LIBRARY'] )
