# Locate Xerces-c
# This module defines
# XERCES_LIBRARY
# XERCES_FOUND, if false, do not try to link to xerces-c 
# XERCES_INCLUDE_DIR, where to find the headers
#
# $XERCES_DIR is an environment variable that would

FIND_PATH(XERCES_INCLUDE_DIR xercesc
    HINTS
       ${XERCES_DIR}
       $ENV{XERCES_DIR}
       $ENV{XERCES_DIR}
       ${DELTA3D_EXT_DIR}
       $ENV{DELTA_ROOT}/ext
       $ENV{DELTA_ROOT}
       $ENV{OSG_ROOT}
    PATH_SUFFIXES
       inc include
)
MARK_AS_ADVANCED(XERCES_INCLUDE_DIR)

MACRO(FIND_XERCES_LIBRARY MYLIBRARY MYLIBRARYNAME)

FIND_LIBRARY(${MYLIBRARY}
    NAMES ${MYLIBRARYNAME} 
    HINTS
       ${XERCES_DIR}
       $ENV{XERCES_DIR}
       $ENV{XERCES_DIR}
       ${DELTA3D_EXT_DIR}
       $ENV{DELTA_ROOT}/ext
       $ENV{DELTA_ROOT}
       $ENV{OSG_ROOT}
    PATH_SUFFIXES
       lib lib64 Frameworks
)
MARK_AS_ADVANCED(${MYLIBRARY})
ENDMACRO(FIND_XERCES_LIBRARY MYLIBRARY MYLIBRARYNAME)

SET(XERCES_LIST Xerces xerces-c xerces-c_2 xerces-c_3)
FIND_XERCES_LIBRARY(XERCES_LIBRARY "${XERCES_LIST}")
SET(XERCES_DEBUG_LIST Xerces xerces-c_2d xerces-c_3D)
FIND_XERCES_LIBRARY(XERCES_LIBRARY_DEBUG "${XERCES_DEBUG_LIST}")

SET(XERCES_FOUND "NO")
IF(XERCES_LIBRARY AND XERCES_INCLUDE_DIR)
    SET(XERCES_FOUND "YES")
ENDIF(XERCES_LIBRARY AND XERCES_INCLUDE_DIR)


