
# This module defines
# OPENVR_LIBRARY
# OSG_OPENVR_VIEWER_LIBRARY
# OSG_OPENVR_VIEWER_INCLUDE_DIR, where to find the headers
#
# $OSG_OPENVR_VIEWER_DIR can be a supplied environment variable that would be the prefix path
#
FIND_PATH(OPENVR_INCLUDE_DIR osgopenvrviewer/export.h
    PATH_SUFFIXES include inc
    HINTS
    $ENV{OSG_OPENVR_VIEWER_INCLUDE_DIR}
    ${DELTA3D_EXT_DIR}
    $ENV{DELTA_ROOT}/ext
)
MARK_AS_ADVANCED(OSG_OPENVR_VIEWER_INCLUDE_DIR)

MACRO(OSG_OPENVR_VIEWER_LIBRARY MYLIBRARY MYLIBRARYNAMES)

FIND_LIBRARY(${MYLIBRARY}
    NAMES ${MYLIBRARYNAMES}
    PATH_SUFFIXES lib
    HINTS
    ${OSG_OPENVR_VIEWER_DIR}
    $ENV{OSG_OPENVR_VIEWER_DIR}
    ${DELTA3D_EXT_DIR}
    $ENV{DELTA_ROOT}/ext
)
MARK_AS_ADVANCED(${MYLIBRARY})
ENDMACRO()


FIND_OSG_OPENVR_VIEWER_LIBRARY(OSG_OPENVR_VIEWER_LIBRARY OsgOpenVR)
FIND_OSG_OPENVR_VIEWER_LIBRARY(OSG_OPENVR_VIEWER_LIBRARY_DEBUG OsgOpenVRd)

SET(OSG_OPENVR_VIEWER_FOUND "NO")
IF(OSG_OPENVR_VIEWER_INCLUDE_DIR AND OSG_OPENVR_VIEWER_LIBRARY)
    if (OSG_OPENVR_VIEWER_LIBRARY_DEBUG)
        SET(OSG_OPENVR_VIEWER_LIBRARIES
           optimized ${OSG_OPENVR_VIEWER_LIBRARY} debug ${OSG_OPENVR_VIEWER_LIBRARY_DEBUG}
        )
    else()
        SET(OSG_OPENVR_VIEWER_LIBRARIES
           ${OSG_OPENVR_VIEWER_LIBRARY}
        )
    endif()
    SET(OSG_OPENVR_VIEWER_FOUND "YES")
ENDIF()
