# Locate Delta3D
# This module defines
# DTCORE_LIBRARY
# DELTA3D_EXT_DIR
# DELTA3D_FOUND, if false, do not try to link to gdal 
# DELTA3D_INCLUDE_DIR, where to find the headers
#
# $DELTA3D_DIR is an environment variable that would
# correspond to the ./configure --prefix=$DELTA3D
#
# Created by David Guthrie. 

set(DELTA_DIR ${CMAKE_SOURCE_DIR})
set(DELTA3D_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/inc)
set(DELTA3D_LIB_DIR ${CMAKE_BINARY_DIR}/lib)

#where to find the Delta3D "ext" folder.  Look for one of the headers that might be in there.
SET(DELTA3D_EXT_DIR ${DELTA_DIR}/ext CACHE PATH "The root of the Delta3D external dependency folder")

IF(DELTA3D_EXT_DIR)
  #for aiding FIND_FILE() and FIND_PATH() searches
  list(APPEND CMAKE_PREFIX_PATH ${DELTA3D_EXT_DIR})
  list(APPEND CMAKE_FRAMEWORK_PATH ${DELTA3D_EXT_DIR}/Frameworks)
  list(APPEND CMAKE_INCLUDE_PATH ${DELTA3D_EXT_DIR}/inc)
ENDIF(DELTA3D_EXT_DIR)

SET(DTUTIL_LIBRARY dtUtil)
SET(DTCORE_LIBRARY dtCore)
SET(DTABC_LIBRARY dtABC)
SET(DTDIRECTOR_LIBRARY dtDirector)
SET(DTDIRECTORNODES_LIBRARY dtDirectorNodes)
SET(DTDIRECTORQT_LIBRARY dtDirectorQt)
SET(DTAI_LIBRARY dtAI)
SET(DTGAME_LIBRARY dtGame)
SET(DTPHYSICS_LIBRARY dtPhysics)
SET(DTAUDIO_LIBRARY dtAudio)
SET(DTANIM_LIBRARY dtAnim)
SET(DTGUI_LIBRARY dtGUI)
SET(DTINSPECTORQT_LIBRARY dtInspectorQt)
SET(DTSCRIPT_LIBRARY dtScript)
SET(DTTERRAIN_LIBRARY dtTerrain)
SET(DTNET_LIBRARY dtNet)
SET(DTNETGM_LIBRARY dtNetGM)
SET(DTHLAGM_LIBRARY dtHLAGM)
SET(DTDIS_LIBRARY dtDIS)
SET(DTINPUTPLIB_LIBRARY dtInputPLIB)
SET(DTACTORS_LIBRARY dtActors)
SET(DTANIM_LIBRARY dtAnim)
SET(DTLMS_LIBRARY dtLMS)
SET(DTQT_LIBRARY dtQt)
SET(DTRENDER_LIBRARY dtRender)
SET(DTVOXEL_LIBRARY dtVoxel)
SET(STAGE_LIBRARY STAGE)
SET(TEST_ACTOR_LIBRARY testActorLibrary)
SET(TEST_GAME_ACTOR_LIBRARY testGameActorLibrary)
SET(FIREFIGHTER_DEMO_LIBRARY fireFighter)

# internal helpers
set(DTCORE_LIBRARIES ${DTCORE_LIBRARY})
set(DUTIL_LIBRARIES ${DTUTIL_LIBRARY})
set(DTABC_LIBRARIES ${DTABC_LIBRARY})
set(DTGAME_LIBRARIES ${DTGAME_LIBRARY})


SET(DELTA3D_FOUND "NO")
IF(DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR AND DELTA3D_LIB_DIR)
    SET(DELTA3D_FOUND "YES")
ENDIF(DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR AND DELTA3D_LIB_DIR)
