Import('*')

if env.get('rti') != 0 :

   srcs = SGlob( '*.cpp' )                  
   deps = [ 'dtCore', 'osgSim', 'winsock' ] + rtiLibs
         
   env.BuildLib( 'dtHLA', srcs, deps, ['DT_HLA_LIBRARY'] )
