SConscript( dirs=['testApp',
                  'testAudio', 
                  'testCharacters',
                  'testClouds',
                  'testEffects',
                  'testGUI',
                  'testInput',
                  'testLights',
                  'testMotionModels',
                  'testPhysics',
                  'testSound',
                  'testWeather',
                  'testWidget',
                  'testWin'] )
#SConscript('testHLA')
#SConscript('testPython')
