import os

Import('*')

if OS == 'windows' :
   if mode == 'debug' :
      build = 'Debug'
   else :
      build = 'Release'
else :
   build = '.'

modules = [ 'testApp', 
            'testAudio', 
            'testCharacters', 
            'testClouds', 
            'testEffects', 
            'testGui', 
            'testHla', 
            'testInput', 
            'testLights', 
            'testMotionModels', 
            'testPhysics', 
            'testPython', 
            'testSound', 
            'testWeather', 
            'testWidget', 
            'testWin' ]
   
for module in modules :
   SConscript( dirs=[module], build_dir = os.path.join( module, build ), duplicate = 0 )
