Import('*')

dtUtilSrcs = [  'domain.cpp',
                'matrixutil.cpp',
                'polardecomp.cpp' ]

dtUtilDeps = [ 'osg', 'sg', 'ul' ]
                
if OS == 'windows' :
    dtUtilDeps += ['User32']

dtUtilDeps = [ extLibs[lib] for lib in dtUtilDeps if extLibs.has_key(lib) ]
    
dtUtilLib = env.SharedLibrary( 'dtutil', dtUtilSrcs, CPPDEFINES = env['CPPDEFINES']+['DT_LIBRARY'], LIBS = dtUtilDeps )

env.Alias( 'install', env.Install( '$prefix/lib', dtUtilLib ) )
env.Default( dtUtilLib )
