Import('*')

dtAbcSrcs = [   'application.cpp',
                'baseabc.cpp',
                'weather.cpp',
                'widget.cpp' ]

dtAbcDeps=[ 'dtcore' ]

if OS == 'windows' :
   dtAbcDeps += [ 'User32' ]
    
BuildLib( 'dtabc', dtAbcSrcs, dtAbcDeps, ['DT_LIBRARY'] )
