Import('*')

dtAbcSrcs = [   'application.cpp',
                'baseabc.cpp',
                'weather.cpp',
                'widget.cpp' ]

dtAbcDeps=[ 'dtcore', 'fltk' ]
    
BuildLib( 'dtabc', dtAbcSrcs, dtAbcDeps, ['DT_LIBRARY'] )
