Import('*')

dtHlaSrcs = [   'dis_types.cpp',
                'entity.cpp',
                'rticonnection.cpp' ]

dtHlaLib = env.SharedLibrary( 'dthla', dtHlaSrcs, LIBS=[ 'dtcore', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgUtil', 'osgSim', 'osgText', 'plibsg', 'plibul', 'Producer', 'tinyxml', '$rtiLibName' ] )

env.Alias('install', env.Install( "$prefix/lib", dtHlaLib ) )

Return( 'dtHlaLib' )
