# Build script for the Dynamic Actor Layer module.
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

if OS == 'darwin':
   overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   overrideShSuffix = '.dylib'
else:
   overrideShLink = ''
   overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
srcs = SGlob( '*.cpp' )

if OS != 'windows':
   srcs.remove( 'dtedterrainactorproxy.cpp' )

deps = [ 'dtDAL', 'dtUtil', 'dtCore', 'dtChar', 'dtABC', 'isense', 'ode',
        'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgTerrain', 'osgText',
        'osgUtil', 'osgGA', 'osgSim', 'osgFX', 'osgProducer','cal3d','rbody',
        'gdal', 'ul', 'js', 'Producer', 'opengl', 'User32', 'Advapi32',
        'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm', 'CoreFoundation', 'IOKit',
        'Carbon' ]

if OS == 'windows' :
   deps += [ 'dtSOARX' ]

dtActors = BuildLib( 'dtActors', srcs, deps, ['DT_PLUGIN'],
                     overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix )

if OS == 'darwin':
   Depends(dtActors, libdtDAL)
