# Build script for the testActorLibrary
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

if OS == 'darwin':
   overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   overrideShSuffix = '.dylib'
else:
   overrideShLink = ''
   overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = SGlob('*.cpp')

testGameActorLibraryDeps =[ 'dtGame', 'dtDAL', 'dtUtil', 'dtCore', 'ode', 'OpenThreads', 'osg',
                        'osgDB', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil',
                        'osgGA', 'osgSim', 'osgFX', 'osgProducer', 'ul', 'js',
                        'Producer', 'opengl', 'User32',
                        'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
                        'CoreFoundation', 'IOKit', 'Carbon' ]

if OS == 'windows':
   testGameActorLibraryDeps += ['dtActors']

testGameActorLibrary = env.BuildLib( 'testGameActorLibrary', sources, testGameActorLibraryDeps, ['DT_EXAMPLE_LIBRARY'], 
                             overrideShLinkFlags = overrideShLink,
                             overrideShLibSuffix = overrideShSuffix )

Export('testGameActorLibrary')
