Import('*')

env = env.Copy()

hlaStealthViewer = env.Program( 'hlaStealthViewer', 'main.cpp', LIBS=[ 'dtcore', 'dtabc', 'dthla', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer' ] )

Return( 'hlaStealthViewer' )
