Import('*')

dtGuiSrcs = [   'ceuidrawable.cpp',
                'renderer.cpp',
                'resourceprovider.cpp' ]

dtGuiDeps=[ 'dtcore', 'CEGUIBase', 'xerces-c', 'CEGUIOpenGLRenderer' ]

if OS == 'windows' :
   dtGuiDeps += [ 'User32' ]
    
BuildLib( 'dtgui', dtGuiSrcs, dtGuiDeps, ['DT_LIBRARY'] )
