Import('*')

dtCharSrcs = [  'character.cpp' ]

dtCharLib = env.SharedLibrary( 'dtchar', dtCharSrcs, LIBS=[ 'dtcore', 'osg', 'osgDB', 'plibsg', 'plibul', 'Producer', 'rbody' ] )

env.Alias('install', env.Install( "$prefix/lib", dtCharLib ) )
env.Default( dtCharLib )
