Import('*')

psEditorSrcs = ['main.cpp', 'psEditorGUI.cxx', 'texturepreview.cpp']

psEditorDeps = [ 'dtvis', 'dtabc', 'dtcore' ]

if OS == 'windows' :
   psEditorDeps += [ 'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

BuildProgram( 'psEditor', psEditorSrcs, psEditorDeps )
