Import('*')

bspCompiler = SConscript( 'bspCompiler/SConscript' )
#hlaStealthViewer = SConscript( 'hlaStealthViewer/SConscript' )
psEditor = SConscript( 'psEditor/SConscript' )
viewer = SConscript( 'Viewer/SConscript' )

#Return( 'bspCompiler', 'hlaStealthViewer', 'psEditor', 'viewer' )
#Return( 'bspCompiler', 'psEditor', 'viewer' )
