import os

Import('*')

if OS == 'windows' :
   if mode == 'debug' :
      build = 'Debug'
   else :
      build = 'Release'
else :
   build = '.'

modules = [ 'bspCompiler', 
            'hlaStealthViewer', 
            'psEditor',
            'Viewer' ]
   
for module in modules :
   SConscript( dirs=[module], build_dir = os.path.join( module, build ), duplicate = 0 )
