Import('*')

dtUtilSrcs = [  'domain.cpp',
                'matrixutil.cpp',
                'polardecomp.cpp' ]

libsToLink = [ 'osg', 'sg', 'ul', 'User32' ]

for lib in libsToLink :
   if extLibs.has_key(lib):
      lib = extLibs[lib]

dtUtilLib = env.SharedLibrary( 'dtutil', dtUtilSrcs, LIBS = libsToLink )

env.Alias( 'install', env.Install( '$prefix/lib', dtUtilLib ) )
env.Default( dtUtilLib )
