Import('*')

if OS == 'windows' :

   dtSoarxSrcs = [ 'soarx_base.cpp',
                   'soarx_camera.cpp',
                   'soarx_core.cpp',
                   'soarx_image.cpp',
                   'soarx_render.cpp',
                   'soarx_tbuilder.cpp',
                   'soarxterrain.cpp',
                   'soarx_texture.cpp' ]

   dtSoarxDeps = [ 'gdal', 'osg', 'osgUtil', 'osgDB', 'osgGL2', 'sg', 'tinyxml', 'ul', 'ode', 'OpenGL' ]
   
   if OS == 'windows' :
      dtSoarxDeps += [ 'User32' ]
    
   dtSoarxDeps = [ extLibs[lib] for lib in dtSoarxDeps if extLibs.has_key(lib) ] + ['dtcore']
                    
   dtSoarxLib = env.SharedLibrary( 'dtsoarx', dtSoarxSrcs, CPPDEFINES = env['CPPDEFINES']+['DT_LIBRARY'], LIBS = dtSoarxDeps )
    
   env.Alias( 'install', env.Install( "$prefix/lib", dtSoarxLib ) )
   env.Default( dtSoarxLib )

