Import('*')

if env.get('boost') != 0 :
    testPython = env.Program( 'testPython', 'testpython.cpp', LIBS=[ 'dtcore', 'dtabc', 'dtutil', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'Xxf86vm', 'python2.3', 'gdal' ] )
