import os

Import('*')

if mode == 'debug' :
   boostLib = 'boost_python_debug'
else :
   boostLib = 'boost_python'

if foundLibs.has_key( boostLib ) and foundLibs.has_key( os.path.join('boost','python.hpp') ) :
   if foundLibs[ boostLib ] and foundLibs[ os.path.join('boost','python.hpp') ] :

      testPythonSrcs = ['testpython.cpp']

      testPythonDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal', 'python' ]

      if OS == 'windows' :
         testPythonDeps += ['User32']
      elif OS == 'linux' :
         testPythonDeps += ['Xxf86vm']

      testPythonDeps = [ extLibs[lib] for lib in testPythonDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtutil' ]

      testPython = env.Program( 'testPython', testPythonSrcs, LIBS = testPythonDeps )
