Import('*')

dtVisSrcs = [ 'bspcullcallback.cpp' ]

dtVisDeps = [ 'opengl', 'OpenThreads', 'osg', 'osgDB', 'osgUtil' ] 
dtVisDeps = [ extLibs[lib] for lib in dtVisDeps if extLibs.has_key(lib) ]

dtVisLib = env.SharedLibrary( 'dtvis', dtVisSrcs, CPPDEFINES = env['CPPDEFINES']+['SG_LIBRARY'], LIBS = dtVisDeps  )

env.Alias( 'install', env.Install( "$prefix/lib", dtVisLib ) )
env.Default( dtVisLib )
