Import('*')

if env.get('rti') != 0 :

   srcs = SGlob( '*.cpp' )                  
   deps = [ 'dtCore', 'osgSim', 'winsock' ] + rtiLibs
         
   defines = []
   if OS == 'windows':
      defines = ['DT_HLA_LIBRARY']

   env.BuildLib( 'dtHLA', srcs, deps, defines )
