Import('*')

srcs = env.SGlob( '*.cpp' )
deps = [ 'dtCore', 'dtABC', 'fltk', 'Producer', 'OpenThreads', 'osg', 'osgDB',
         'osgUtil', 'osgText', 'osgGL2', 'osgGA', 'osgParticle', 'osgSim',
         'osgFX', 'osgProducer', 'isense', 'js', 'ul', 'Carbon',
         'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

defines = []
if env['OS'] == 'windows':
   defines = ['DT_INSPECTOR_LIBRARY']
                    
env.BuildLib( 'dtInspector', srcs, deps, defines )
