Import('*')

dtCharSrcs = [  'character.cpp' ]

if OS == 'darwin':
    dtCharDeps=[ 'dtcore', 'cal3d', 'rbody' ] 
else:
    dtCharDeps=[ 'dtcore', 'cal3d', 'rbody', 'rvrutils', 'rcfg' ] 

if OS == 'windows' :
   dtCharDeps += ['User32']
    
BuildLib( 'dtchar', dtCharSrcs, dtCharDeps, ['DT_LIBRARY'] )
