Import('*')

srcs = env.SGlob('*.cpp')

deps = [ 'opengl', 'OpenThreads', 'osg', 'osgDB', 'osgUtil' ] 

defines = []
if env['OS'] == 'windows':
   defines = ['OSG_LIBRARY']

env.BuildLib( 'dtBSP', srcs, deps, defines )
