# Build script for the testActorLibrary
import glob
import sys
import delta3d

# Import the variables defined in the global SConstruct build script.
Import ('*')

overrideShLink = ''
overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = env.SGlob('*.cpp')

testActorLibraryDeps =[ 'dtDAL', 'dtUtil', 'dtCore', 'ode', 'OpenThreads', 'osg',
                        'osgDB', 'osgParticle', 'osgText', 'osgUtil',
                        'osgSim', 'osgFX',
                        'Producer', 'opengl', 'dtSORAX', 'User32',
                        'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
                        'CoreFoundation', 'IOKit', 'Carbon', 'dtActors' ]


testActorLibrary = env.BuildLib( 'testActorLibrary', sources, testActorLibraryDeps, ['DT_PLUGIN'], 
                             overrideShLinkFlags = overrideShLink,
                             overrideShLibSuffix = overrideShSuffix )

Export('testActorLibrary')
