Import('*')

testEffectsSrcs = ['testeffects.cpp']

testEffectsDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal', 'osgGA', 'osgFX', 'osgProducer', 'osgSim' ]

if OS == 'windows' :
   testEffectsDeps += ['User32']
elif OS == 'linux' :
   testEffectsDeps += ['Xxf86vm']

testEffectsDeps = [ extLibs[lib] for lib in testEffectsDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtutil' ]

testEffects = env.Program( 'testEffects', testEffectsSrcs, LIBS = testEffectsDeps )
