Import('*')

if env.get('rti') != 0 :

   srcs = env.SGlob( '*.cpp' )                  
   deps = [ 'dtCore', 'osgSim', 'winsock' ] + env['rtiLibs']
         
   defines = []
   if env['OS'] == 'windows':
      defines = ['DT_HLA_LIBRARY']

   env.BuildLib( 'dtHLA', srcs, deps, defines )
