Import('*')

env = env.Copy()

testClouds = env.Program( 'testClouds', 'testclouds.cpp', LIBS=[ 'dtcore', 'dtabc', 'dtutil', 'gui_fl', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer', 'tinyxml', 'Xxf86vm', 'fltk' ] )
