# Build script for the Dynamic Actor Layer module.
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

# Grab all the sources from the DAL source directory.
srcs = env.SGlob('*.cpp')

deps =  [ 'dtDAL', 'dtGame', 'dtUtil', 'dtCore', 'dtAI', 'ode', 
          'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgText',
          'osgUtil', 'osgSim', 'osgFX', 'rbody', 'rvrutils',
          'rcfgscript', 'cal3d', 'opengl',
          'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32',
          'uuid', 'Xxf86vm', 'CoreFoundation', 'IOKit', 'Carbon', 'winsock']

defines = []
#if env['OS'] == 'windows':
defines = ['DT_LMS_LIBRARY']

libdtLMS = env.BuildLib( 'dtLMS', srcs, deps, defines, prefixHeader = "inc/prefix/dtgameprefix.h" )

Export ('libdtLMS')
