Import('*')

env = env.Copy()

testWidget = env.Program( 'testWidget', ['MyWidget.cpp', 'MyWindow.cpp', 'TestWidget.cxx' ], LIBS=[ 'dtcore', 'dtabc', 'dtutil', 'fltk', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer', 'tinyxml', 'Xxf86vm' ] )

Return( 'testWidget' )
