// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifdef _MSC_VER
#	pragma warning(push)
#	pragma warning(disable : 4244) // for warning C4244: '=' : conversion from 'short' to 'uchar', possible loss of data
#endif

#include "TestWidget.h"

#ifdef _MSC_VER
#	pragma warning(pop)
#endif

#include <assert.h>

TestWidget::TestWidget() {
  Fl_Window* w;
  { Fl_Window* o = MainWindow = new Fl_Window(640, 480);
    w = o;
    o->user_data((void*)(this));
    { MyWindow* o = ViewPort = new MyWindow(0, 0, 640, 480, "ViewPort");
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    o->set_non_modal();
    o->end();
  }
}

void TestWidget::make_window() {
  MainWindow->show();
}
