Import('*')

dtAbcSrcs = [   'application.cpp',
                'baseabc.cpp',
                'event.cpp',
                'state.cpp',
                'statemanager.cpp',
                'weather.cpp',
                'widget.cpp' ]

dtAbcDeps=[ 'dtcore', 'fltk' ]
    
BuildLib( 'dtabc', dtAbcSrcs, dtAbcDeps, ['DT_LIBRARY'] )
