import os

Import('*')

srcs = env.SGlob( '*.cpp' )

deps=[ 'dtCore', 'dtUtil', 'ul', 'js', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgParticle',
       'osgText', 'osgUtil', 'osgSim', 'osgFX','Producer', 'opengl',
       'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
       'CoreFoundation', 'IOKit', 'Carbon' ]

defines = []

if env['OS'] == 'windows':
   defines = ['DT_INPUT_PLIB_LIBRARY', 'NOMINMAX']
    
env.BuildLib( 'dtInputPLIB', srcs, deps,  defines, prefixHeader = 'inc/prefix/dtcoreprefix.h')
