Import('*')

env = env.Copy()

hlaStealthViewer = env.Program( 'hlaStealthViewer', 'main.cpp', LIBS=[ 'dtcore', 'dtabc', 'dthla', 'dtutil', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer', 'tinyxml', 'Xxf86vm', 'rtis', 'fedtime13', 'mcast', 'mpiif', 'msgstats', 'rid', 'timers', 'urlreader', 'bitvector', 'vterm', 'netutil', 'if', 'mempool', 'mersenne', 'parser', 'rti13' ] )

Return( 'hlaStealthViewer' )
