Import('*')

viewerSrcs = SGlob( '*.cpp' ) + SGlob( '*.cxx' )

viewerDeps = [ 'dtDAL', 'dtCore', 'dtABC', 'dtUtil', 'dtChar',
               'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

BuildProgram( 'dtViewer', viewerSrcs, viewerDeps )
