Import('*')

gui_flSrcs = [  'gui_fltk.cpp',
                'guimgr.cpp' ]

gui_flLib = env.SharedLibrary( 'gui_fl', gui_flSrcs, LIBS=[ 'dtcore', 'fltk', 'OpenThreads', 'osg', 'plibsg', 'plibul', 'Producer', 'tinyxml' ] )

env.Alias('install', env.Install( "$prefix/lib", gui_flLib ) )

Return( 'gui_flLib' )
