Import('*')

if foundLibs.has_key('boost_python') :

   testPythonSrcs = ['testpython.cpp']

   testPythonDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal', 'python' ]

   if OS == 'windows' :
      testPythonDeps += ['User32']
   elif OS == 'linux' :
      testPythonDeps += ['Xxf86vm']

   testPythonDeps = [ extLibs[lib] for lib in testPythonDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtutil' ]

   testPython = env.Program( 'testPython', testPythonSrcs, LIBS = testPythonDeps )