import os

Import('*')

if CheckForBoost() :

   testPythonSrcs = ['testpython.cpp']

   testPythonDeps = [ 'dtcore', 'dtabc', 'dtutil', 'python' ]

   BuildProgram( '#bin/testPython', testPythonSrcs, testPythonDeps )
