//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OSGHelper.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_BILLBOARD                   6
#define IDS_BILL_MODE                   7
#define IDS_BILL_AXIS                   8
#define IDS_BILL_NORMAL                 9
#define IDS_BILL_NODES                  10
#define IDS_OSGHELPER                   11
#define IDS_STATESET_NODES              12
#define IDS_STATESET                    13
#define IDS_STATESET_RENDER_HINT        14
#define IDS_STATESET_RENDER_MODE        15
#define IDS_STATESET_NORMALIZE          16
#define IDS_STATESET_CULLFACE           17
#define IDS_STATESET_BIN_NUMBER         18
#define IDS_STATESET_BIN_NAME           19
#define IDS_LOD                         20
#define IDS_LOD_NODES                   21
#define IDS_LOD_CENTER                  22
#define IDS_LOD_MIN                     23
#define IDS_LOD_MAX                     24
#define IDS_PICK_GEOM_OBJECT            25
#define IDS_SEQUENCE                    26
#define IDS_SEQUENCE_INTERVAL           27
#define IDS_SEQUENCE_DURATION           28
#define IDS_SEQUENCE_MODE               29
#define IDS_SEQUENCE_TIME               30
#define IDS_SEQUENCE_NODES              31
#define IDS_SEQUENCE_APPROACH           32
#define IDS_SEQUENCE_SAMPLE_NODE        33
#define IDS_SEQUENCE_FRAME_PER_SAMPLE   34
#define IDS_NODEMASK_VALUE              35
#define IDS_NODEMASK_NODES              36
#define IDS_NODEMASK                    37
#define IDS_SWITCH                      38
#define IDS_SWITCH_NODES                39
#define IDS_IMPOSTOR_VALUE              40
#define IDS_IMPOSTOR_NODES              41
#define IDS_IMPOSTOR                    42
#define IDS_OCCLUDER                    43
#define IDS_OCCLUDER_NODES              44
#define IDS_NODEMASK_MODE               45
#define IDS_LOD_USEPAGED                46
#define IDS_PAGEDLOD_FILENAME           47
#define IDS_STATESET_TURNOFFLIGHTING    48
#define IDS_VISIBILITYGROUP             49
#define IDS_VISIBILITYGROUP_VOLUME      50
#define IDS_VISIBILITYGROUP_NODES       51
#define IDS_POLYGONOFFSET               52
#define IDS_POLYGONMODE                 53
#define IDS_RENDERBIN                   54
#define IDS_GLMODE                      55
#define IDS_STATESET_RENDERBIN_ENABLE   56
#define IDS_STATESET_POLYMODE_ENABLE    57
#define IDS_STATESET_POLYMODE_FRONTFACE 58
#define IDS_STATESET_POLYMODE_BACKFACE  59
#define IDS_STATESET_POLYOFF_ENABLE     60
#define IDS_STATESET_POLYOFF_FACTOR     61
#define IDS_STATESET_POLYOFF_UNIT       62
#define IDS_STATESET_POLYOFF_DEPTHFUNC  63
#define IDS_STATESET_USEALPHABLENDING   64
#define IDS_SWITCH_ENABLE_CHILDREN      65
#define IDS_GROUP                       66
#define IDS_DOF_NODES                   67
#define IDD_PANEL                       101
#define IDD_BILLBOARD                   102
#define IDD_LOD                         104
#define IDD_SEQUENCE                    105
#define IDD_VISIBILITYGROUP             106
#define IDS_DOF                         107
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_ROT_AXIAL                   1003
#define IDC_ROT_WORLD                   1004
#define IDC_ROT_EYE                     1005
#define IDC_RENDER_ENCLOSE              1006
#define IDC_HRP                         1006
#define IDC_BILL_SPIN1                  1007
#define IDC_BILL_EDIT1                  1008
#define IDC_STATESET_NODELIST           1009
#define IDC_POLYOFF_UNIT_EDIT           1009
#define IDC_BILL_EDIT7                  1009
#define IDC_STATESET_PICKNODE           1010
#define IDC_POLYOFF_UNIT_SPIN           1010
#define IDC_BILL_SPIN7                  1010
#define IDC_STATESET_REMOVENODE         1011
#define IDC_BILL_EDIT13                 1011
#define IDC_BILL_SPIN13                 1012
#define IDC_RPH                         1013
#define IDC_ROT_EYE2                    1014
#define IDC_RHP                         1014
#define IDC_RENDER_INHERIT              1015
#define IDC_RENDER_USE                  1016
#define IDC_RENDER_OVERRIDE             1017
#define IDC_GLMODE_CULLFACE             1018
#define IDC_GLMODE_NORMALIZE            1019
#define IDC_STATESET_BIN_NAME           1020
#define IDD_STATESET                    1020
#define IDC_STATESET_BIN_EDIT           1021
#define IDD_NODEMASK                    1021
#define IDC_STATESET_BIN_SPIN           1022
#define IDD_SWITCH                      1022
#define IDC_LOD_PICKNODE1               1023
#define IDD_IMPOSTOR                    1023
#define IDC_GLMODE_TURNOFFLIGHTING      1023
#define IDC_LOD_PICKNODE2               1024
#define IDD_OCCLUDER                    1024
#define IDC_LOD_PICKNODE3               1025
#define IDD_POLYGONOFFSET               1025
#define IDC_LOD_MIN_EDIT1               1026
#define IDD_POLYGONMODE                 1026
#define IDC_LOD_MIN_SPIN1               1027
#define IDD_RENDERBIN                   1027
#define IDC_LOD_MAX_EDIT1               1028
#define IDD_GLMODE                      1028
#define IDC_LOD_MAX_SPIN1               1029
#define IDC_LOD_CENTER_Y_EDIT           1030
#define IDC_LOD_CENTER_Y_SPIN           1031
#define IDC_LOD_CENTER_Z_EDIT           1032
#define IDC_LOD_CENTER_Z_SPIN           1033
#define IDC_LOD_CENTER_X_EDIT           1034
#define IDC_LOD_CENTER_X_SPIN           1035
#define IDC_LOD_MIN_EDIT2               1036
#define IDC_LOD_MIN_SPIN2               1037
#define IDC_LOD_MAX_EDIT2               1038
#define IDC_LOD_MAX_SPIN2               1039
#define IDC_LOD_MIN_EDIT3               1040
#define IDC_LOD_MIN_SPIN3               1041
#define IDC_LOD_MAX_EDIT3               1042
#define IDC_LOD_MAX_SPIN3               1043
#define IDC_SEQUENCE_TIME_EDIT1         1044
#define IDC_SEQUENCE_TIME_EDIT2         1045
#define IDC_SEQUENCE_TIME_EDIT3         1046
#define IDC_SEQUENCE_TIME_EDIT4         1047
#define IDC_SEQUENCE_TIME_EDIT5         1048
#define IDC_LOD_PICKNODE4               1049
#define IDC_SEQUENCE_SAMPLE_EDIT        1049
#define IDC_LOD_MIN_EDIT4               1050
#define IDC_SEQUENCE_TIME_SPIN1         1050
#define IDC_LOD_MIN_SPIN4               1051
#define IDC_SEQUENCE_SAMPLE_SPIN        1051
#define IDC_LOD_MAX_EDIT4               1052
#define IDC_LOD_MAX_SPIN4               1053
#define IDC_LOD_PICKNODE5               1054
#define IDC_LOD_MIN_EDIT5               1055
#define IDC_SEQUENCE_TIME_SPIN2         1055
#define IDC_LOD_MIN_SPIN5               1056
#define IDC_LOD_MAX_EDIT5               1057
#define IDC_LOD_MAX_SPIN5               1058
#define IDC_SEQUENCE_TIME_SPIN3         1059
#define IDC_SEQUENCE_TIME_SPIN4         1060
#define IDC_SEQUENCE_TIME_SPIN5         1061
#define IDC_SEQUENCE_PICKNODE1          1062
#define IDC_SEQUENCE_PICKNODE2          1063
#define IDC_SEQUENCE_PICKNODE3          1064
#define IDC_SEQUENCE_PICKNODE4          1065
#define IDC_SEQUENCE_PICKNODE5          1066
#define IDC_SEQUENCE_BEGIN_EDIT         1067
#define IDC_SEQUENCE_END_EDIT           1068
#define IDC_SEQUENCE_BEGIN_SPIN         1069
#define IDC_SEQUENCE_END_SPIN           1070
#define IDC_SEQUENCE_LOOP               1071
#define IDC_SEQUENCE_SWING              1072
#define IDC_SEQUENCE_SAMPLE_PICKNODE    1074
#define IDC_SEQUENCE_SAMPLE             1075
#define IDC_SEQUENCE_SPEED_EDIT         1077
#define IDC_SEQUENCE_SPEED_SPIN         1078
#define IDC_SEQUENCE_REPS_EDIT          1079
#define IDC_SEQUENCE_REPS_SPIN          1080
#define IDC_SEQUENCE_START              1081
#define IDC_SEQUENCE_STOP               1082
#define IDC_SEQUENCE_PAUSE              1083
#define IDC_SEQUENCE_RESUME             1084
#define IDC_SEQUENCE_STATIC             1085
#define IDC_NODEMASK_EDIT               1086
#define IDC_NODEMASK_SPIN               1087
#define IDC_NODEMASK_REMNODE            1089
#define IDC_SWITCH_REMNODE              1091
#define IDC_IMPOSTOR_EDIT               1092
#define IDC_IMPOSTOR_SPIN               1093
#define IDC_IMPOSTOR_REMNODE            1095
#define IDC_OCCLUDER_REMNODE            1097
#define IDC_MULTIPLE_PICKNODE           1098
#define IDC_CHECK1                      1099
#define IDC_LOD_USEPAGED                1099
#define IDC_POLYGONOFFSET_ENABLE        1099
#define IDC_GLMODE_ALPHABLENDING        1099
#define IDC_SWITCH_ENABLE_CHILDREN2     1100
#define IDC_NODEMASK_TERRAIN            1102
#define IDC_NODEMASK_COLLISION          1103
#define IDC_SWITCH_ENABLE_CHILDREN1     1103
#define IDC_NODEMASK_NO_COLLISION       1104
#define IDC_SWITCH_ENABLE_CHILDREN4     1104
#define IDC_NODEMASK_CUSTOM             1105
#define IDC_SWITCH_ENABLE_CHILDREN5     1105
#define IDC_SWITCH_ENABLE_CHILDREN6     1106
#define IDC_SWITCH_ENABLE_CHILDREN7     1107
#define IDC_SWITCH_ENABLE_CHILDREN8     1108
#define IDC_PAGEDLOD_FILENAME           1109
#define IDC_SWITCH_ENABLE_CHILDREN9     1109
#define IDC_VISIBILITYGROUP_REMNODE     1110
#define IDC_SWITCH_ENABLE_CHILDREN10    1110
#define IDC_VISIBILITYGROUP_VOLUME      1111
#define IDC_POLYOFF_FACTOR_EDIT         1115
#define IDC_POLYOFF_FACTOR_SPIN         1116
#define IDC_POLYGONOFFSET_DEPTHFUNC     1117
#define IDC_PMFF_RADIO1                 1118
#define IDC_PMFF_RADIO2                 1119
#define IDC_PMFF_RADIO3                 1120
#define IDC_PMBF_RADIO1                 1121
#define IDC_PMBF_RADIO2                 1122
#define IDC_PMBF_RADIO3                 1123
#define IDC_POLYGONMODE_ENABLE          1124
#define IDC_RENDERBIN_ENABLE            1125
#define IDC_PRH                         1128
#define IDC_PHR                         1129
#define IDC_HPR                         1130
#define IDC_BILL_PICKNODE               1157
#define IDC_PICKNODE                    1157
#define IDC_NODE_MOVE_UP                1158
#define IDC_NODE_MOVE_DOWN              1159
#define IDC_LIST                        1333
#define IDC_REMOVE_BILL                 1334
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_EDIT2                       1491
#define IDC_BILL_EDIT2                  1491
#define IDC_EDIT3                       1492
#define IDC_BILL_EDIT3                  1492
#define IDC_EDIT4                       1493
#define IDC_BILL_EDIT4                  1493
#define IDC_EDIT5                       1494
#define IDC_BILL_EDIT5                  1494
#define IDC_EDIT6                       1495
#define IDC_BILL_EDIT6                  1495
#define IDC_SPIN                        1496
#define IDC_BILL_EDIT8                  1496
#define IDC_SPIN2                       1497
#define IDC_BILL_SPIN2                  1497
#define IDC_SPIN3                       1498
#define IDC_BILL_SPIN3                  1498
#define IDC_SPIN4                       1499
#define IDC_BILL_SPIN4                  1499
#define IDC_SPIN5                       1500
#define IDC_BILL_SPIN5                  1500
#define IDC_SPIN6                       1501
#define IDC_BILL_SPIN6                  1501
#define IDS_GROUP_NODES                 1502
#define IDC_BILL_SPIN8                  1502
#define IDD_GROUP                       1503
#define IDD_OSGGROUP                    1503
#define IDC_BILL_EDIT9                  1503
#define IDD_DOFTRANSFORM                1504
#define IDC_BILL_SPIN9                  1504
#define IDC_BILL_EDIT10                 1505
#define IDC_BILL_SPIN10                 1506
#define IDC_BILL_EDIT11                 1507
#define IDC_BILL_SPIN11                 1508
#define IDC_BILL_EDIT12                 1509
#define IDC_BILL_SPIN12                 1510
#define IDC_BILL_EDIT14                 1511
#define IDC_BILL_SPIN14                 1512
#define IDC_BILL_EDIT15                 1513
#define IDC_BILL_SPIN15                 1514
#define IDC_BILL_EDIT16                 1515
#define IDC_BILL_SPIN16                 1516
#define IDC_BILL_EDIT17                 1517
#define IDC_BILL_SPIN17                 1518
#define IDC_BILL_EDIT18                 1519
#define IDC_BILL_SPIN18                 1520
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
