Import('*')

testSrcs = [ 'testNetwork.cpp', 'main.cpp', 'mynetwork.cpp', 'packets.cpp' ]

testDeps = [ 'dtcore', 'dtabc', 'dtutil', 'dtNet', 'gne', 'HawkNL' ]

if OS == 'windows' :
   testDeps += [ 'winsock' ]

BuildProgram( '#bin/testNetwork', testSrcs, testDeps )
