import os

Import('*')

if OS == 'windows' :
   if mode == 'debug' :
      build = 'Debug'
   else :
      build = 'Release'
else :
   build = '.'

modules = [ 'dtABC', 'dtAudio', 'dtChar', 'dtCore', 'dtHLA', 'dtScript', 'dtUtil', 'dtVis', 'gui_fl', 'python', 'soarx' ]
   
for module in modules :
   SConscript( dirs=[module], build_dir = os.path.join( module, build ), duplicate = 0 )
