Import('*')

SConscript(dirs=[ 'dtABC', 'dtAudio', 'dtChar', 'dtCore', 'dtUtil', 'dtVis', 'gui_fl' ])

#SConscript(dirs=[ 'python' ])
#SConscript(dirs=[ 'soarx' ])

env.Depends('dtCore','dtUtil')
env.Depends('dtABC','dtCore')
env.Depends('dtChar','dtCore')
env.Depends('gui_fl','dtCore')
