Import('*')

SConscript(dirs=[ 'dtABC', 'dtAudio', 'dtChar', 'dtCore', 'dtUtil', 'dtVis', 'gui_fl' ])

#SConscript(dirs=[ 'python' ])
#SConscript(dirs=[ 'soarx' ])

env.Depends('dtcore','dtutil')
env.Depends('dtabc','dtcore')
env.Depends('dtchar','dtcore')
env.Depends('gui_fl','dtcore')
