Import('*')

srcs = env.SGlob( '*.cpp' )
deps = [ 'dtCore', 'dtInputPLIB', 'dtGUI', 'dtABC', 'dtUtil', 'cal3d',
             'CEGUIBase', 'CEGUIOpenGLRenderer' ]

env.BuildProgram( 'testInput', srcs, deps )
