import os

Import('*')

modules = [ 'testActorLibrary',
            'testGameActorLibrary' ]

if env.get("buildExamples"):
   modules += [
            'testApp',
            'testAI',
            'testAAR', 
            'testAudio',
            'testAnim',
            'testBumpMap',
            'testCharacters',
            'testClouds',
            'testEffects',
            'testGameEnvironment',
            'testGUI',
            'testHLA',
            'testInput',
            'testLights',
            'testMap',
            'testMotionModels',
            'testMultiWin',
            'testNetwork',
            'testPhysics',
            'testPython',
            'testRecorder',
            'testShaders',
            'testSound',
            'testStateManager',
            'testTerrain',
            'testTrigger',
            'testWeather',
            'testWidget',
            'testWin']

# TODO: this should defintely be using the env['TOOLS'] list and extracting the 'default' cxx tool,
#       problem is that on win32 the c_compiler and cxx_compiler are the same, so there's one
#       less element in the list, so we can't use an index to find the proper tool. instead we
#       need to query what scons chooses from the list and actually uses...
if env['OS'] == 'windows' :
   tool = 'msvc'
elif env['OS'] == 'linux' or env['OS'] == 'darwin' :
   tool = 'g++'

for module in modules :
   SConscript( dirs=[module], build_dir = os.path.join( buildProductsDir, module, env['OS']+'-'+tool+'-'+mode ), duplicate = 0 )
