Import('*')

srcs = env.SGlob( '*.cpp' ) + env.SGlob( '*.cxx' )

# Build the icon
if env['OS'] == 'windows' and env.has_key('MSVS') :
   if env['MSVS']['VERSION'] < 8.0 :
      srcs += env.RES( 'psEditor.rc' )

deps = [ 'dtABC', 'dtCore', 'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

env.BuildProgram( 'psEditor', srcs, deps, buildAppBundle = 0 )
