import os

Import('*')

srcs = env.SGlob( '*.cpp' )

deps=[ 'dtUtil', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGA', 'osgParticle',
       'osgText', 'osgUtil', 'osgSim', 'osgFX','osgViewer', 'opengl',
       'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
       'CoreFoundation', 'IOKit', 'Carbon' ]

defines = []

defines = ['DT_CORE_LIBRARY']
if env['OS'] == 'windows':
   srcs.remove( 'deltawin_x11.cpp' )
   srcs.remove( 'deltawin_carbon.cpp' )
   srcs.remove( 'uniqueid_linux.cpp' )
   srcs.remove( 'uniqueid_macosx.cpp' )
elif env['OS'] == 'linux':
   srcs.remove( 'deltawin_win32.cpp' )
   srcs.remove( 'deltawin_carbon.cpp' )
   srcs.remove( 'uniqueid_win32.cpp' )
   srcs.remove( 'uniqueid_macosx.cpp' )
elif env['OS'] == 'darwin':
   srcs.remove( 'deltawin_x11.cpp' )
   srcs.remove( 'deltawin_win32.cpp' )
   srcs.remove( 'uniqueid_linux.cpp' )
   srcs.remove( 'uniqueid_win32.cpp' )
    
env.BuildLib( 'dtCore', srcs, deps,  defines, prefixHeader = 'inc/prefix/dtcoreprefix.h')
