Import('*')

dtCharSrcs = [  'character.cpp' ]

dtCharDeps = [ 'osg', 'osgDB', 'sg', 'ul', 'Producer', 'rbody', 'rvrutils', 'cal3d' ]
                
if OS == 'windows' :
    dtCharDeps += ['User32']
    
dtCharDeps = [ extLibs[lib] for lib in dtCharDeps if extLibs.has_key(lib) ]

dtCharLib = env.SharedLibrary( 'dtchar', dtCharSrcs, CPPDEFINES = env['CPPDEFINES']+['DT_LIBRARY'], LIBS = dtCharDeps+['dtcore'] )

env.Alias('install', env.Install( "$prefix/lib", dtCharLib ) )
env.Default( dtCharLib )
