# Build script for the Dynamic Actor Layer module.
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

# Grab all the sources from the DAL source directory.
sources = SGlob('*.cpp')

dtDALDeps =[ 'dtutil', 'dtCore', 'dtChar', 'dtaudio', 'dtabc', 'glgui', 'isense', 'ode', 
	'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 
	'osgGA', 'osgSim', 'osgFX', 'osgProducer','rbody', 'rvrutils', 'rcfgscript','gdal', 
        'cal3d', 'ul', 'js', 
	'Producer', 'tinyxml', 'opengl' ]

if OS == 'windows' :
   dtDALDeps += [ 'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32' ]
elif OS == 'linux':
   dtDALDeps += [ 'uuid', 'Xxf86vm' ]
elif OS == 'darwin':
   dtDALDeps += [ 'CoreFoundation', 'IOKit', 'Carbon' ]

    
libdtDAL = BuildLib( 'dtDAL', sources, dtDALDeps, ['DT_LIBRARY'] )

Export ('libdtDAL')
