Import('*')

srcs = SGlob( '*.cpp' )

deps = [ 'dtCore', 'cal3d', 'rbody', 'dtUtil', 'isense',
         'OpenThreads', 'osg', 'osgDB', 'osgParticle',
         'osgText', 'osgUtil', 'osgGA', 'osgSim', 'osgFX', 'osgProducer',
         'ul', 'js', 'Producer', 'opengl', 'rbody', 'rvrutils', 'rcfgscript' ] 
    
env.BuildLib( 'dtChar', srcs, deps, ['DT_CHAR_LIBRARY'] )
