Import('*')

if env.get('rti') :

   srcs = env.SGlob( '*.cpp' )

   # Build the icon
   if env['OS'] == 'windows' and env.has_key('MSVS') :
      if env['MSVS']['VERSION'] < 8.0 : 
         srcs += env.RES( 'hlaStealthViewer.rc' )

   deps = [ 'dtCore', 'dtABC', 'dtHLA', 'dtUtil'  ]

   env.BuildProgram( 'hlaStealthViewer', srcs, deps )
