Import('*')

testSrcs = ['testcharacters.cpp']

testDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal', 'rbody', 'rvrutils', 'cal3d', 'rcfgscript', 'gdal', 'osgGA', 'osgFX', 'osgProducer', 'osgSim' ]

if OS == 'windows' :
   testDeps += ['User32']
elif OS == 'linux' :
   testDeps += ['Xxf86vm']

testDeps = [ extLibs[lib] for lib in testDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dtchar', 'dtutil' ]

env.Program( 'testCharacters', testSrcs, LIBS = testDeps )
