Import('*')

if env.get('rti') != 0 :

   testSrcs = ['testhla.cpp']

   testDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal' ] + rtiSLibs

   if OS == 'windows' :
      testDeps += ['User32']
   elif OS == 'linux' :
      testDeps += ['Xxf86vm']

   testDeps = [ extLibs[lib] for lib in testDeps if extLibs.has_key(lib) ] + [ 'dtcore', 'dtabc', 'dthla', 'dtutil' ]

   env.Program( 'testHLA', testSrcs, LIBS = testDeps )
