Import('*')

srcs = env.SGlob( '*.cpp' )
deps = [ 'dtCore', 'dtABC', 'dtUtil', 'dtGUI',
             'CEGUIBase', 'CEGUIOpenGLRenderer', 'CEGUIWindowsLook' ]

env.BuildProgram( 'testGUI', srcs, deps )
