Import('*')

testSrcs = ['testgui.cpp']

testDeps = [ 'dtcore', 'dtabc', 'dtutil', 'dtgui', 'CEGUIBase', 'CEGUIOpenGLRenderer',
   'CEGUIWindowsLook' ]

BuildProgram( '#bin/testGUI', testSrcs, testDeps )
