// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef fltkwindow_h
#define fltkwindow_h
#include <FL/Fl.H>
#include <assert.h>
#include <FL/Fl_Window.H>
#include <FL/X.h>
#include "Fl_P51_Window.h"

class FLTKWindow {
public:
  FLTKWindow();
private:
  Fl_Window *MainWindow;
  Fl_P51_Window *ViewPort;
public:
  void make_window( int argc, const char** argv );
};
#endif
