Import('*')

viewerSrcs = env.SGlob( '*.cpp' ) + env.SGlob( '*.cxx' )

# Build the icon
if env['OS'] == 'windows' and env.has_key('MSVS') :
   if env['MSVS']['VERSION'] < 8.0 :
      viewerSrcs += env.RES( 'Viewer.rc' )

defines = []

viewerDeps = [ 'dtDAL', 'dtCore', 'dtABC', 'dtUtil',
               'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]

env.BuildProgram( 'viewer', viewerSrcs, viewerDeps, defines, buildAppBundle = 0 )
