Import('*')

srcs = env.SGlob('*.cpp')

deps = [ 'dtCore', 'dtAI', 'dtDAL', 'fltk', 'dtUtil', 'OpenThreads', 'osg', 'osgDB','osgGA',
         'osgParticle', 'osgText', 'osgUtil', 'osgSim', 'osgFX',
	 'osgViewer', 'xerces-c', 'opengl', 'User32' ]

defines = []
if env['OS'] == 'windows':
   defines = ['DT_ABC_LIBRARY']       

env.BuildLib( 'dtABC', srcs, deps, defines, prefixHeader = 'inc/prefix/dtcoreprefix.h')
