Import('*')

import glob

srcs = env.SGlob('*.cpp')
deps = ['dtGame', 'dtNet', 'dtCore', 'dtDAL', 'ncurses', 'dtUtil', 'osg', 'gne', 'HawkNL', ]
       
env.BuildLib( 'dtNetGM', srcs, deps, ['DT_NETGM_LIBRARY'])
