import glob
import os
import string

Import('*')

if env.get('rti') != 0 :

   testHlaDeps = [ 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgSim', 'osgTerrain', 'osgText', 'osgUtil', 'sg', 'ul', 'js', 'Producer', 'tinyxml', 'gdal' ]
                
   if OS == 'windows' :
      testHlaDeps += ['User32']
   elif OS == 'linux' :
      testHlaDeps += ['Xxf86vm']

   testHlaDeps = [ extLibs[lib] for lib in testHlaDeps if extLibs.has_key(lib) ] + rtiSLibs + [ 'dtcore', 'dtabc', 'dthla', 'dtutil' ]

   testHla = env.Program( 'testHLA', 'testhla.cpp', LIBS = testHlaDeps )
