Import('*')

testSrcs = ['testinput.cpp']

testDeps = [ 'dtcore', 'dtgui', 'dtabc', 'dtutil', 'cal3d', 'CEGUIBase', 'CEGUIOpenGLRenderer',
   'CEGUIWindowsLook' ]

BuildProgram( 'testInput', testSrcs, testDeps )
