# Build script for the Dynamic Actor Layer module.
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

overrideShLink = ''
overrideShSuffix = ''

defines = []

# Grab all the sources from the DAL source directory.
srcs = env.SGlob( '*.cpp' )

if env['foundLibs'][env['extLibs']['rbody']] == 'notFound':
   defines += ['NO_DTCHAR']

deps = [ 'dtAnim', 'dtDAL', 'dtUtil', 'dtCore', 'dtChar', 'dtABC', 'dtAudio', 'ode',
        'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgText',
        'osgUtil', 'osgSim', 'osgFX','cal3d','rbody', 'opengl', 'User32', 'Advapi32',
        'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm', 'CoreFoundation', 'IOKit',
        'Carbon', 'dtGame']

if env['OS'] == 'windows':
   defines += ['DT_PLUGIN']

dtActors = env.BuildLib( 'dtActors', srcs, deps, defines,
                     overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix, prefixHeader = 'inc/prefix/dtdalprefix.h' )

if env['OS'] == 'darwin':
   Depends(dtActors, libdtDAL)
