Import('*')

gui_flSrcs = [  'gui_fltk.cpp',
                'guimgr.cpp' ]

gui_flDeps=[ 'dtCore', 'dtABC', 'fltk', 'Producer', 'OpenThreads', 'osg', 'osgDB',
             'osgUtil', 'osgText', 'osgGL2', 'osgGA', 'osgParticle', 'osgSim',
             'osgTerrain', 'osgFX', 'osgProducer', 'isense', 'js', 'ul', 'Carbon',
             'User32', 'Gdi32', 'shell32', 'Advapi32', 'ole32' ]
                    
BuildLib( 'gui_fl', gui_flSrcs, gui_flDeps, ['DT_LIBRARY'] )
