Import('*')

srcs = SGlob('*.cpp')

deps = [ 'dtCore', 'dtDAL', 'fltk', 'dtUtil', 'isense', 'OpenThreads', 'osg', 'osgDB',
         'osgParticle', 'osgText', 'osgUtil', 'osgGA', 'osgSim', 'osgFX',
         'osgProducer', 'ul', 'js', 'Producer', 'xerces-c', 'opengl', 'User32' ]
       
BuildLib( 'dtABC', srcs, deps, ['DT_ABC_LIBRARY'] )
