import os

Import('*')

if CheckForBoost() :

   srcs = SGlob( '*.cpp' )
   deps = [ 'dtCore', 'dtABC', 'dtUtil', 'dtScript', 'python' ]

   extraLink = []
   if OS == 'windows':
      extraLink = ['/NODEFAULTLIB:'+extLibs['python']+'_d']

   BuildProgram( 'testPython', srcs, deps, [], extraLink )
