bspCompiler = SConscript( 'bspCompiler/SConscript' )
#hlaStealthViewer = SConscript('hlaStealthViewer')
psEditor = SConscript( 'psEditor/SConscript' )
viewer = SConscript( 'Viewer/SConscript' )

Return( 'bspCompiler', 'psEditor', 'viewer' ) #add hla
