Import('*')


dtUtilSrcs = SGlob('*.cpp')

dtUtilDeps =[ 'OpenThreads', 'Producer', 'osg', 'osgDB', 'ul', 'xerces-c' ]

if OS == 'windows' :
    dtUtilDeps += ['User32']

BuildLib( 'dtutil', dtUtilSrcs, dtUtilDeps, ['DT_LIBRARY'] )
