Import('*')

dtAudioSrcs = [ 'audiomanager.cpp',
                'listener.cpp',
                'sound.cpp',
                'soundeffectbinder.cpp' ]
                
dtAudioDeps = [ 'dtcore', 'openal' ]

if OS == 'windows' :
   dtAudioDeps += [ 'alut', 'User32' ]

BuildLib( 'dtaudio', dtAudioSrcs, dtAudioDeps, ['DT_LIBRARY'] )
