#!/bin/sh

cd ../../lib

ln -sf libdtcorebindings.so dtCore.so
ln -sf libdtabcbindings.so dtABC.so
ln -sf libdtcharbindings.so dtChar.so
ln -sf libdtaudiobindings.so dtAudio.so
ln -sf libdtguiflbindings.so dtGUIFl.so
#ln -sf libdthlabindings.so dtHLA.so
#ln -sf libdtsoarxbindings.so dtSOARX.so

