Import('*')

srcs = SGlob( '*.cpp' ) + SGlob( '*.cxx' )
deps = [ 'dtCore', 'dtABC', 'dtUtil', 'User32', 'Gdi32',
         'shell32', 'Advapi32', 'ole32', 'Xxf86vm', 'winsock', 'Comctl32' ]

env.BuildProgram( 'testWidget', srcs, deps )
