# Build script for the testActorLibrary
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

overrideShLink = ''
overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
sources = env.SGlob('*.cpp')

testGameActorLibraryDeps =[ 'dtGame', 'dtDAL', 'dtUtil', 'dtCore', 'ode', 'OpenThreads', 'osg',
                            'osgDB', 'osgParticle', 'osgText', 'osgUtil',
                            'osgSim', 'osgFX',
                            'Producer', 'opengl', 'User32',
                            'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm',
                            'CoreFoundation', 'IOKit', 'Carbon', 'dtActors' ]

testGameActorLibrary = env.BuildLib( 'testGameActorLibrary', sources, testGameActorLibraryDeps, ['DT_EXAMPLE_LIBRARY'], 
                             overrideShLinkFlags = overrideShLink,
                             overrideShLibSuffix = overrideShSuffix )

Export('testGameActorLibrary')
