# Locate OpenEXR
# This module defines
# OPENEXR_LIBRARY
# OPENEXR_FOUND, if false, do not try to link to OpenEXR 
# OPENEXR_INCLUDE_DIR, where to find the headers
#
# $OPENEXR_DIR is an environment variable that would
# correspond to the ./configure --prefix=$OPENEXR_DIR
#
# Created by Robert Osfield. 
FIND_PATH(OPENEXR_INCLUDE_DIR OpenEXR/half.h
    PATH_SUFFIXES include inc
    HINTS
    $ENV{OPENEXR_DIR}
    ${DELTA3D_EXT_DIR}
    $ENV{DELTA_ROOT}/ext
)
MARK_AS_ADVANCED(OPENEXR_INCLUDE_DIR)

MACRO(FIND_OPENEXR_LIBRARY MYLIBRARY MYLIBRARYNAMES)

FIND_LIBRARY(${MYLIBRARY}
    NAMES ${MYLIBRARYNAMES}
    PATH_SUFFIXES lib
    HINTS
    ${OPENEXR_DIR}
    $ENV{OPENEXR_DIR}
    ${DELTA3D_EXT_DIR}
    $ENV{DELTA_ROOT}/ext
)
MARK_AS_ADVANCED(${MYLIBRARY})
ENDMACRO()


#FIND_OPENEXR_LIBRARY(OPENEXR_IlmIlf_LIBRARY  IlmImf)
#FIND_OPENEXR_LIBRARY(OPENEXR_IlmThread_LIBRARY  IlmThread)
#FIND_OPENEXR_LIBRARY(OPENEXR_Iex_LIBRARY  Iex)
FIND_OPENEXR_LIBRARY(OPENEXR_Half_LIBRARY  Half)

SET(OPENEXR_FOUND "NO")
#IF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmIlf_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Half_LIBRARY)
IF(OPENEXR_INCLUDE_DIR AND OPENEXR_Half_LIBRARY)
    SET(OPENEXR_LIBRARIES
        #${OPENEXR_IlmIlf_LIBRARY}
        #${OPENEXR_IlmThread_LIBRARY}
        ${OPENEXR_Half_LIBRARY}
        #${OPENEXR_Iex_LIBRARY}
    )
    SET(OPENEXR_FOUND "YES")
ENDIF()
