Import('*')

srcs = env.SGlob( '*.cpp' )

# Build the icon
if env['OS'] == 'windows' :
   srcs += env.RES( 'bspCompiler.rc' )

deps = [ 'dtBSP' ]

env.BuildProgram( 'bspCompiler', srcs, deps, buildAppBundle = 0)
