# Build script for the Dynamic Actor Layer module.
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

overrideShLink = ''
overrideShSuffix = ''

# Grab all the sources from the DAL source directory.
srcs = SGlob( '*.cpp' )

deps = [ 'dtDAL', 'dtUtil', 'dtCore', 'dtChar', 'dtABC', 'dtAudio', 'isense', 'ode',
        'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgText',
        'osgUtil', 'osgGA', 'osgSim', 'osgFX', 'osgProducer','cal3d','rbody',
        'gdal', 'ul', 'js', 'Producer', 'opengl', 'User32', 'Advapi32',
        'Rpcrt4', 'Winmm', 'Gdi32', 'uuid', 'Xxf86vm', 'CoreFoundation', 'IOKit',
        'Carbon', 'dtGame']

defines = []
if OS == 'windows':
   defines = ['DT_PLUGIN']

dtActors = env.BuildLib( 'dtActors', srcs, deps, defines,
                     overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix, prefixHeader = 'inc/prefix/dtdalprefix.h' )

if OS == 'darwin':
   Depends(dtActors, libdtDAL)
