Import('*')

if env.get('rti') != 0 :

   srcs = env.SGlob( '*.cpp' )                  
   deps = [ 'dtGame', 'dtDAL', 'dtABC', 'dtCore', 'osgSim', 'winsock' ] + env['rtiLibs']
         
   defines = []
   #if env['OS'] == 'windows':
   defines = ['DT_HLAGM_LIBRARY']

   env.BuildLib( 'dtHLAGM', srcs, deps, defines )
