# Build script for the Dynamic Actor Layer module.
import glob
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

if OS == 'darwin':
   overrideShLink = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   overrideShSuffix = '.so'
else:
   overrideShLink = ''
   overrideShSuffix = ''


# Grab all the sources from the DAL source directory.
sources = glob.glob('*.cpp')

if OS != 'windows':
	sources.remove('dtedterrainactorproxy.cpp')

dtActorsDeps =['dtDAL', 'dtutil', 'dtcore', 'dtchar', 'dtabc', 'glgui', 'isense', 'ode',
        'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil',
        'osgGA', 'osgSim', 'osgFX', 'osgProducer','cal3d','rbody','gdal', 'sg', 'ul', 'js',
        'Producer', 'tinyxml', 'opengl' ]

if OS == 'windows' :
   dtActorsDeps += [ 'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32' ]
elif OS == 'linux':
   dtActorsDeps += [ 'uuid', 'Xxf86vm' ]
elif OS == 'darwin':
   dtActorsDeps += [ 'CoreFoundation', 'IOKit', 'Carbon' ]

BuildLib( 'dtActors', sources, dtActorsDeps, ['DT_PLUGIN'], 
	overrideShLinkFlags = overrideShLink, overrideShLibSuffix = overrideShSuffix )
