Import('*')

srcs = SGlob('*.cpp')
deps = [ 'dtCore', 'python' ]

extraLink = []
if OS == 'windows':
   extraLink = ['/NODEFAULTLIB:'+extLibs['python']+'_d']
       
BuildLib( 'dtScript', srcs, deps, ['DT_SCRIPT_LIBRARY'], extraLink )
