Import('*')

env = env.Copy()

testWeather = env.Program( 'testWeather', 'testweather.cpp', LIBS=[ 'dtcore', 'dtabc', 'dtutil', 'gui_fl', 'fltk', 'glgui', 'isense', 'ode', 'OpenThreads', 'osg', 'osgDB', 'osgGL2', 'osgParticle', 'osgTerrain', 'osgText', 'osgUtil', 'plibsg', 'plibul', 'plibjs', 'Producer', 'tinyxml', 'Xxf86vm', 'gdal' ] )

Return( 'testWeather' )
