Import('*')

dtScriptSrcs = [ 'scriptmanager.cpp' ]
dtScriptDeps = [ 'dtcore' ]

extraLink = []
if OS == 'windows':
   extraLink = ['/NODEFAULTLIB:'+extLibs['python']+'_d']
       
BuildLib( 'dtscript', dtScriptSrcs, dtScriptDeps, ['DT_LIBRARY'], extraLink )

 
