# Build script for the Dynamic Actor Layer module.
import sys

# Import the variables defined in the global SConstruct build script.
Import ('*')

# Grab all the sources from the DAL source directory.
srcs = SGlob('*.cpp')

deps =  [ 'dtUtil', 'dtCore', 'dtChar', 'isense', 'ode', 
          'OpenThreads', 'osg', 'osgDB', 'osgParticle', 'osgText',
          'osgUtil', 'osgGA', 'osgSim', 'osgFX', 'osgProducer', 'rbody', 'rvrutils',
          'rcfgscript', 'gdal', 'cal3d', 'ul', 'js', 'Producer', 'opengl',
          'User32', 'Advapi32', 'Rpcrt4', 'Winmm', 'Gdi32',
          'uuid', 'Xxf86vm', 'CoreFoundation', 'IOKit', 'Carbon' ]

defines = []
if OS == 'windows':
   defines = ['DT_DAL_LIBRARY']

libdtDAL = env.BuildLib( 'dtDAL', srcs, deps, defines, prefixHeader = "inc/prefix/dtdalprefix.h" )

Export ('libdtDAL')
